### ISSUE TITLE
Rozdelenie 2. milestone

### ISSUE THREAD

**Issue by charlliz** [jkuchar/PA165-java-project#39]
- [x] Aja: Car, ApplicationRejectedRecord
- [x] Honza: CarAuditLogItem, RentApplication #42 
- [x] Riso: User, ApplicationApprovedRecord
- [x] Jakub: RentRecord, ReturnRecord
